apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hocs-data-service
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: hocs-data-service
  targetCPUUtilizationPercentage: 80
