---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hocs-data-service
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hocs-data-service
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: hocs-data-service
        version: {{.VERSION}}
    spec:
      containers:
      - name: hocs-data-service
        image: quay.io/ukhomeofficedigital/hocs-data-service:{{.VERSION}}
        env:
          - name: JAVA_OPTS
            value: '-Xms150m -Xmx768m'
          - name: SERVER_PORT
            value: '8080'
          - name: ENDPOINTS_INFO_ENABLED
            value: 'false'
          - name: SPRING_PROFILES_ACTIVE
            value: 'postgres'
          - name: SLS_DB_HOSTNAME
            valueFrom:
              secretKeyRef:
                name: hocs-rds-access
                key: endpoint
          - name: SLS_DB_PORT
            valueFrom:
              secretKeyRef:
                name: hocs-rds-access
                key: port
          - name: SLS_DB_NAME
            valueFrom:
              secretKeyRef:
                name: hocs-rds-access
                key: database_name
          - name: SLS_SCHEMA_NAME
            value:
              'hocs_data_service'
          - name: SLS_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: hocs-rds-access
                key: username
          - name: SLS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hocs-rds-access
                key: password
          - name: ENV_HOCS_API_USER
            valueFrom:
              secretKeyRef:
                name: hocs-api-access
                key: api_user
          - name: ENV_HOCS_API_PASSWORD
            valueFrom:
              secretKeyRef:
                name: hocs-api-access
                key: api_password
          - name: ENV_HOCS_API_HOST
            valueFrom:
              secretKeyRef:
                name: hocs-api-access
                key: api_host
        resources:
          limits:
            memory: 1024Mi
            cpu: 400m
          requests:
            memory: 1024Mi
            cpu: 200m
        ports:
          - name: http
            containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            httpHeaders:
              - name: X-probe
                value: kubelet
          initialDelaySeconds: 180
          periodSeconds: 20
          timeoutSeconds: 10
        imagePullPolicy: Always
      - name: vault-sidekick
        image: quay.io/ukhomeofficedigital/vault-sidekick:v0.2.0
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        args:
          - -output=/etc/nginx/secrets
          - -tls-skip-verify=true
          - -cn=pki:services/${NAMESPACE}/pki/issue/default:common_name=hocs-data-service.${NAMESPACE}.svc.cluster.local,file=/etc/nginx/secrets/hocs-data-service,fmt=bundle
        env:
          - name: VAULT_ADDR
            value: "https://vault.vault.svc.cluster.local:8200"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: VAULT_TOKEN
            valueFrom:
              secretKeyRef:
                name: store-token
                key: token
        volumeMounts:
          - mountPath: /etc/nginx/secrets
            name: secrets
      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy:v3.2
        imagePullPolicy: Always
        resources:
         limits:
          memory: "100Mi"
          cpu: 100m
         requests:
          memory: "50Mi"
          cpu: 100m
        env:
          - name: PROXY_SERVICE_HOST
            value: '127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
          - name: ENABLE_UUID_PARAM
            value: 'FALSE'
          - name: HTTPS_REDIRECT
            value: 'FALSE'
          - name: SERVER_CERT
            value: /etc/nginx/secrets/hocs-data-service-bundle.pem
          - name: SERVER_KEY
            value: /etc/nginx/secrets/hocs-data-service-key.pem
        volumeMounts:
          - name: secrets
            mountPath: /etc/nginx/secrets
            readOnly: true
        ports:
          - name: https
            containerPort: 10443
      volumes:
      - name: secrets
        emptyDir:
          medium: "Memory"
