---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.class: nginx-external
    ingress.kubernetes.io/auth-type: basic
    ingress.kubernetes.io/auth-secret: hocs-basic-auth
    ingress.kubernetes.io/auth-realm: "Authentication Required"
    stable.k8s.psg.io/kcm.provider: http
  labels:
    stable.k8s.psg.io/kcm.class: default
  name: hocs-data-service
spec:
  rules:
  - host: {{.DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-data-service
          servicePort: 443
        path: /  
  - host: {{.LEGACY_DOMAIN_NAME}}
    http:
      paths:
      - backend:
          serviceName: hocs-data-service
          servicePort: 443
        path: /
  tls:
  - hosts:
    - {{.DOMAIN_NAME}}
    - {{.LEGACY_DOMAIN_NAME}}
    secretName: letsencrypt-hocs-data-service
